### PR TITLE
Schema patch 112_113_c - fix panel attrib_id

### PR DESCRIPTION
**Pull request by dglemos**
Tested on prod-2 `old_schema_G2P_2024_11_28`

### CODE REVIEW

**Review by olaaustine — APPROVED** [review]
LGTM

**Comment by dglemos** [comment]
@olaaustine, thanks!
I'm going to update branches and live db.

**Review by seeta-ramaraju — APPROVED** [review]
LGTM

**Comment by olaaustine** [comment]
I am updating branches.

**Comment by dglemos** [comment]
Live db and website updated

**Pull request merged**
