### PR TITLE
Adding incomplete penetrance

### PR DESCRIPTION
**Pull request by olaaustine**
[ENSVAR-5515](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5515)

### CODE REVIEW

**Review by dglemos — CHANGES_REQUESTED** [review]
You need to add the new attrib to the file sql/attrib_entries.sql
I also found an issue in that file - not related to this PR but could you please add the fix? in line 101 there is a typo:
`INSERT IGNORE INTO attrib (atrrib_id, attrib_type_id, value) VALUES (81, 11, 'moderate');`
atrrib_id -> attrib_id

Edit: same typo in line 135

**Comment by olaaustine** [comment]
> You need to add the new attrib to the file sql/attrib_entries.sql I also found an issue in that file - not related to this PR but could you please add the fix? in line 101 there is a typo: `INSERT IGNORE INTO attrib (atrrib_id, attrib_type_id, value) VALUES (81, 11, 'moderate');` atrrib_id -> attrib_id
> 
> Edit: same typo in line 135

Thank you for noticing this. 
This has been updated. 
Thank you

**Review by dglemos — COMMENTED** [review]
Sorry, there's one more thing. The patch has to be added here: https://github.com/EBI-G2P/ensembl-gene2phenotype/blob/d3b17bf2543f4a5239e5b7a30c07fafc51b55f18/sql/table.sql#L25

**Comment by olaaustine** [comment]
> Sorry, there's one more thing. The patch has to be added here:
> 
> https://github.com/EBI-G2P/ensembl-gene2phenotype/blob/d3b17bf2543f4a5239e5b7a30c07fafc51b55f18/sql/table.sql#L25

Updated. Thank you

**Review by dglemos — APPROVED** [review]

**Comment by dglemos** [comment]
Merged into release/109 and master

**Pull request merged**
